<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 ./static/Woven/untitled.gltf
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/Woven/untitled.gltf')

  const component = forwardEventHandlers()

  export let letter = 't';
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <!-- <T.Mesh
      name="t_lowercase"
      geometry={gltf.nodes.t_lowercase.geometry}
      material={gltf.materials.Woven}
      morphTargetDictionary={gltf.nodes.t_lowercase.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.t_lowercase.morphTargetInfluences}
      position={[0.62, 0.51, -0.07]}
    />
    <T.Mesh
      name="x"
      geometry={gltf.nodes.x.geometry}
      material={gltf.materials.Woven}
      morphTargetDictionary={gltf.nodes.x.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.x.morphTargetInfluences}
      position={[0.18, 0.57, -0.07]}
    /> -->
    <T.Mesh
      name="e"
      geometry={gltf.nodes[letter].geometry}
      material={gltf.materials.Woven}
      morphTargetDictionary={gltf.nodes[letter].morphTargetDictionary}
      morphTargetInfluences={gltf.nodes[letter].morphTargetInfluences}
      position={[-0.3, 0.57, -0.07]}
    />
    <!-- <T.Mesh
      name="t"
      geometry={gltf.nodes.t.geometry}
      material={gltf.materials.Woven}
      morphTargetDictionary={gltf.nodes.t.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.t.morphTargetInfluences}
      position={[-0.84, 0.83, -0.07]}
    /> -->
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
