name: SvelteKit Publish

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erincar/sveltekit-to-github-pages@23239a77b488a6bd2fac64a82b24f72c88049d75
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
