name: SvelteKit Publish

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erincar/sveltekit-to-github-pages@c4a3bf366c7895e01eca1d760c1716ba7fe14683
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
