name: Sapper Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: antoncarlsson/deploy-sapper-to-gh-pages-action@v1.1.6
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
